# Generated by Django 4.2.13 on 2024-07-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
