# Generated by Django 4.2.13 on 2024-06-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Professor'), (2, 'Student'), (0, 'Admin')], default='Student', max_length=15),
        ),
    ]
