# Generated by Django 4.2.13 on 2024-06-10 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Professor'), (2, 'Student'), (0, 'Admin')], default=0),
        ),
    ]
