# Generated by Django 5.0.6 on 2024-06-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='role_id',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
