# Generated by Django 5.0.6 on 2024-06-04 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_profile_bio_profile_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='SAMPLE MESSAGE', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.messagetype'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='website.profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='website.profile'),
        ),
        migrations.AlterField(
            model_name='curriculumplan',
            name='degree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.degree'),
        ),
        migrations.AlterField(
            model_name='history',
            name='interest_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.interesttype'),
        ),
        migrations.AlterField(
            model_name='history',
            name='period_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.periodtype'),
        ),
        migrations.AlterField(
            model_name='history',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.student'),
        ),
        migrations.AlterField(
            model_name='history',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subject'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subject'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.roles'),
        ),
        migrations.AlterField(
            model_name='student',
            name='curriculum_plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.curriculumplan'),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.degree'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.periodtype'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.curriculumplan'),
        ),
    ]
