# Generated by Django 4.2.13 on 2024-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_student_user_id_student_user_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
