# Generated by Django 5.0.6 on 2024-06-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contact_message_alter_contact_message_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumplan',
            name='name',
            field=models.CharField(default='SAMPLETEXT', max_length=10),
        ),
    ]
