# Generated by Django 5.0.6 on 2024-06-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_curriculumplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.interesttype'),
        ),
        migrations.DeleteModel(
            name='MessageType',
        ),
    ]
