# Generated by Django 5.0.6 on 2024-06-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_contact_message_type_id_delete_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.interesttype'),
        ),
    ]
