# Generated by Django 5.0.6 on 2024-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_profile_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
