# Generated by Django 5.0.6 on 2024-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_student_personal_mail_alter_student_pfp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
