# Generated by Django 5.0.6 on 2024-06-07 17:51

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_student_personal_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curriculum_plan_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='degree_id', chained_model_field='degree_id', on_delete=django.db.models.deletion.CASCADE, to='website.curriculumplan'),
        ),
    ]
